### ISSUE TITLE
False negative for the curl-without-fail rule

### ISSUE THREAD

**Issue by tymonx** [jimschubert/docked#2]
The `curl-without-fail` rule incorrectly fails:

```plaintext
   ⨯   Critical              DC:curl-without-fail                 Avoid using curl without the silent failing option -f/--fail
```

With this simple example:

```dockerfile
FROM alpine:3.14.2

RUN apk --no-cache update && apk --no-cache add curl
```

**Comment by jimschubert** [comment]
@tymonx thanks for finding that!

I hadn't expected anyone to start checking out this project until I'd updated the command checks to pass through a shell parser. I'd put it off because I thought it was going to be difficult, but turned out to be less than an hour of work. I wish my day job was like that :)

Fixed via abd07322fa0 and released as [v0.3.0](https://github.com/jimschubert/docked/releases/tag/v0.3.0). Could you give it a try?

https://github.com/jimschubert/docked/blob/d3935ba3c6b0a8e786c395d70004dd1eeeed40e0/docked_test.go#L235-L242
